name: ğŸ” Check schema

on:
  push:
    paths:
      - schema/**
      - .github/workflows/check-schema.yaml

defaults:
  run:
    working-directory: schema

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
